const topics = [
    {
        title: "TOPIC 29: DISCOURSE ANALYSIS AND ARTICULATION",
        outline: [
            { text: "1. Introduction", info: "<b>Halliday and Hasan, 1976</b><br> Text can be defined as “a stretch of language that can form the process of communication”" },
            { text: "2. Understanding discourse", info: "Defining <b>discourse</b> begins with its link to context.<br> <b>Discourse analysis</b>: linguistics now takes the view that language is not just the composition of sentences, but those aspects of language that go beyond the sentence. <br> <b>Types of discourse functions</b>: <br> - Declarative (statements)<br>- Interrogative (questions)<br>- Imperative (directives)<br>- Exclamative (exclamations)" },
            { text: "3. Levels of communication", info: "<b>Levels of communication</b>: <br> - Vocabulary<br> - Grammar<br> - Structure<br> - Genre<br> - Non-verbal<br> - Conversational codes" },
            { text: "4. Cohesion and coherence", info: "The feature that distinguishes a text from a disconnected sequence of sentences is <b>cohesion</b>; cohesion provides a text with <b>coherence (or texture)</b> and makes it hang together as a significant unit. In this sense, <b>Hallidday and Hasan</b> believe that a set of sentences will or will not constitute a text depending on the cohesive relationships within and between sentences, which create a <b>“texture”</b>. <br><br> According to <b>Halliday and Hasan (2014)</b>, cohesion is the combination of <b>register</b>, or how we speak, and <b>various devices</b> that make a text coherent." },
            { text: "4.1. Register", info: "Register can be divided into two classes: <br> <b>- Open Register</b> <br> <b>- Closed Register</b>" },
            { text: "4.2. Cohesive devices", info: "According to Halliday and Hasan (2014), cohesion is created through five devices: <br> - <b>Reference</b>:<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Exophoric <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Endophoric: <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9632; Anaphora <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9632; Cataphora <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Reference items <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9632; Personal pronouns <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9632; Comparatives <br>- <b>Substitution</b>:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Nominal substitution <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Verbal substitution <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Clausal substitution <br>- <b>Ellipsis</b>:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Nominal ellipsis <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Verbal ellipsis <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Clausal ellipsis <br>- <b>Lexical cohesion</b>:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Reiteration <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Collocation <br>- <b>Conjunction (Connectors and linkers)</b>:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Additive connectors <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Contrastive connectors <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Cause and result connectors <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Time connectors <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Purpose connectors <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Disjunctive connectors" },
            { text: "5. Texture of discourse", info: "The main components of texture within the sentence are the <b>theme system</b> and the <b>information system</b>." },
            { text: "6. Deixis", info: "- Personal deixis <br> - Place deixis <br> - Time deixis <br> - Discourse deixis <br> - Social deixis"},
            { text: "7. Relevance of this topic in the classroom"},
            { text: "8. Conclusion"},
            { text: "9. Bibliography"}
        ]
    },
    {
        title: "TOPIC 32: NARRATIVE TEXTS: STRUCTURE AND CHARACTERISTICS",
        outline: [
            { text: "1. Introduction", info: "<b>Halliday and Hasan, 1976</b><br> Text can be defined as “a stretch of language that can form the process of communication”"},
            { text: "2. Characteristics and definition of narrative texts", info: "Any narrative involves a teller and a tale. <br><br> Narrations share certain common features, including: <br> - <b>A degree of artificial fabrication</b> <br> - <b>Narratives must have a teller</b><br> - <b>Narratives exploit displacement</b> <br><br> The different styles are: <br> - <b>Neutral style</b> <br> - <b>Informal style</b> <br> - <b>Formal style</b> <br> - <b>Evocative style</b> <br> - <b>Hyperbolic style</b> <br> - <b>Persuasive style</b> <br> - <b>Technical style</b> <br> - <b>Illustrative style</b> <br> - <b>Metaphorical style</b> <br>"},
            { text: "3. Basic structure: Universals", info: "Narrative texts show a number of common elements known as <b>universals</b>. Narrative universals are not always present in all narrative texts. Some of them do, and they are called “obligatory elements”. Other elements are either optional or iterative, meaning they are repeated in the same text: <br> - <b>Title</b> <br> - <b>Orientation</b> <br> - <b>Goal</b> <br> - <b>Action</b> <br> - <b>Climax</b> <br> - <b>Conclusion</b> <br> - <b>The moral or evaluation</b>"},
            { text: "4. The articulation of narrative texts", info: "- <b>Time</b>: <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Anachrony <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Flashbacks <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Flashforwards <br> - <b>Narrator and Focalisation</b> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Dramatized and undramatized narrator (Types of narrators) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; External (Types of focalisation) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Internal (Types of focalisation) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Fixed focalisation (Types of focalisation) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Variable focalisation (Types of focalisation) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Multiple focalisation (Types of focalisation) <br> - <b>Characters:</b> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; giver-receiver / subject-object / helper-opponent <br> - <b>Setting</b> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Causal <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Analogical"},
            { text: "5. Varieties of narrative", info: "- <b>Anecdote</b> <br> - <b>Fable</b> <br> - <b>Parable</b>"},
            { text: "6. Structure of narrative texts"},
            { text: "6.1. Introduction"},
            { text: "6.2. Development"},
            { text: "6.3. Conclusion"},
            { text: "7. Relevance of this topic in the classroom"},
            { text: "8. Conclusion"},
            { text: "9. Bibliography"}
        ]
    },
    {
        title: "TOPIC 33: DESCRIPTIVE TEXTS. STRUCTURE & CHARACTERISTICS",
        outline: [
            { text: "1. Introduction", info: "<b>Ushchapovska, 2020</b> <br> “Descriptive texts are an assertive type of text which aim to characterize the natural phenomena, architectural structures, objects, actions and people with a detailed list of their features, properties and characteristics”."},
            { text: "2. Structure of descriptive texts", info: "- <b>The referent</b> <br> - <b>The qualities</b>"},
            { text: "2.1. Technical descriptions", info: "Order of adjectives according to the Cambridge Dictionary: <br> 1.- Opinion <br> 2.- Size <br> 3.- Physical quality <br> 4.- Shape <br> 5.- Age <br> 6.- Colour <br> 7.- Origin <br> 8.- Material <br> 9.- Type <br> 10.- Purpose"},
            { text: "2.2. Description of people and places", info: "The main points that identify a person are: <br> - <b>Sex</b> <br> - <b>Special features</b> <br> - <b>Size</b> <br> - <b>Personality</b> <br> - <b>Age group</b> <br><br> Describing places: <br> - <b>Outdoor descriptions</b> <br> - <b>Indoor descriptions</b>"},
            { text: "2.3. Description of emotions", info: "The description of emotions does not follow a specific structure, as it includes whatever the addresser deems suitable. The objective is to make the reader feel whatever a person is going through."},
            { text: "2.4. Description of a process", info: "When dealing with a process, the following structure must be considered: <br> - <b>Elements are presented</b> <br> - <b>Phases and element functions are explained</b> <br> - <b>Expected outcome and results are advanced</b>"},
            { text: "3. Principles of descriptive texts"},
            { text: "3.1. Regulative principles", info: "- <b>The efficiency of a text</b> <br> - <b>The effectiveness of a text</b> <br> - <b>The appropriateness of a text</b>"},
            { text: "3.2. Constitutive principles", info: "- <b>Situationality</b> <br> - <b>Informativity</b> <br> - <b>Intertextuality</b> <br> - <b>Intentionality</b> <br> - <b>Acceptability</b>"},
            { text: "4. Characteristics of descriptive texts"},
            { text: "4.1. Descriptions to convey a setting"},
            { text: "4.2. Descriptions used with characters"},
            { text: "4.3. Descriptions to set the mood", info: "- <b>Subjective descriptions</b> <br> - <b>Objective descriptions</b>"},
            { text: "5. Text and context", info: "In 1923, anthropologist <b>Malinowski</b> introduced the concept of context of situation, referring to extra-linguistic factors influencing a text. He observed that cultural background shapes individual psychology, challenging Jung and Freud’s theories on the collective subconscious. While translating English texts for the Trobriand Islanders of New Guinea, he found cultural differences difficulted comprehension, leading him to provide contextual instructions for clarity. <br><br> The concept of context of situation was re-elaborated by Firth, who distinguished four main elements which have to be born in mind in relation to descriptive text: <br> - <b>The participants in the situation</b> <br> - <b>The action of the participants</b> (including verbal and non-verbal actions) <br> - The relevant features that affect the act of communication, that is, <b>the surrounding objects and events</b> <br> - <b>The effects of the verbal action</b> <br><br> Hymes categorizes the speech situation in terms of components. According to him, the higher number of known elements, the better understanding of the text. Hymes’ components are: <br> - Form and content of the message (<b>setting</b>) <br> - <b>Participants</b> (intention and effect) <br> - <b>Key communication</b> <br> - <b>Medium</b> (norms of interaction) <br> - <b>Genre</b> (type of text) <br><br> A more abstract interpretation has been offered by Halliday and Hasan. They proposed three headings: <br> - <b>Field</b> <br> - <b>Mode</b> <br> - <b>Tenor</b>"},
            { text: "6. Relevance of this topic in the classroom"},
            { text: "7. Conclusion"},
            { text: "8. Bibliography"}
        ]
    },
    {
        title: "TOPIC 34: ARGUMENTATIVE TEXTS. STRUCTURE & CHARACTERISTICS",
        outline: [
            { text: "1. Introduction", info: "<b>Halliday and Hasan, 1976</b><br> Text can be defined as “a stretch of language that can form the process of communication”"},
            { text: "1.1. Understanding argumentative texts", info: "Types of argumentative texts: <br> - <b>Subjective</b> <br> - <b>Objective</b> <br> - <b>Scientific</b>"},
            { text: "2. Cohesion and coherence in argumentative texts", info: "The feature that distinguishes a text from a disconnected sequence of sentences is <b>cohesion</b>; cohesion provides a text with <b>coherence (or texture)</b> and makes it hang together as a significant unit. In this sense, <b>Hallidday and Hasan</b> believe that a set of sentences will or will not constitute a text depending on the cohesive relationships within and between sentences, which create a <b>“texture”</b>. <br><br> According to <b>Halliday and Hasan (2014)</b>, cohesion is the combination of <b>register</b>, or how we speak, and <b>various devices</b> that make a text coherent."},
            { text: "2.1. Register", info: "Register can be divided into two classes: <br> <b>- Open Register</b> <br> <b>- Closed Register</b>"},
            { text: "2.2. Cohesive devices", info: "According to Halliday and Hasan (2014), cohesion is created through five devices: <br> - <b>Reference</b>:<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Exophoric <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Endophoric: <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9632; Anaphora <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9632; Cataphora <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Reference items <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9632; Personal pronouns <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9632; Comparatives <br>- <b>Substitution</b>:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Nominal substitution <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Verbal substitution <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Clausal substitution <br>- <b>Ellipsis</b>:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Nominal ellipsis <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Verbal ellipsis <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Clausal ellipsis <br>- <b>Lexical cohesion</b>:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Reiteration <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Collocation <br>- <b>Conjunction (Connectors and linkers)</b>:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Additive connectors <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Contrastive connectors <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Cause and result connectors <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Time connectors <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Purpose connectors <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Disjunctive connectors"},
            { text: "3. Text and context", info: "In 1923, anthropologist <b>Malinowski</b> introduced the concept of context of situation, referring to extra-linguistic factors influencing a text. He observed that cultural background shapes individual psychology, challenging Jung and Freud’s theories on the collective subconscious. While translating English texts for the Trobriand Islanders of New Guinea, he found cultural differences difficulted comprehension, leading him to provide contextual instructions for clarity. <br><br> The concept of context of situation was re-elaborated by Firth, who distinguished four main elements which have to be born in mind in relation to descriptive text: <br> - <b>The participants in the situation</b> <br> - <b>The action of the participants</b> (including verbal and non-verbal actions) <br> - The relevant features that affect the act of communication, that is, <b>the surrounding objects and events</b> <br> - <b>The effects of the verbal action</b> <br><br> Hymes categorizes the speech situation in terms of components. According to him, the higher number of known elements, the better understanding of the text. Hymes’ components are: <br> - Form and content of the message (<b>setting</b>) <br> - <b>Participants</b> (intention and effect) <br> - <b>Key communication</b> <br> - <b>Medium</b> (norms of interaction) <br> - <b>Genre</b> (type of text) <br><br> A more abstract interpretation has been offered by Halliday and Hasan. They proposed three headings: <br> - <b>Field</b> <br> - <b>Mode</b> <br> - <b>Tenor</b>"},
            { text: "4. Principles of an argumentative text"},
            { text: "4.1. Regulative principles", info: "- <b>The efficiency of a text</b> <br> - <b>The effectiveness of a text</b> <br> - <b>The appropriateness of a text</b>"},
            { text: "4.2. Constitutive principles", info: "- <b>Situationality</b> <br> - <b>Informativity</b> <br> - <b>Intertextuality</b> <br> - <b>Intentionality</b> <br> - <b>Acceptability</b>"},
            { text: "5. Characteristics of argumentative texts"},
            { text: "5.1. Structure of argumentative texts", info: "Traditionally, argumentative texts should be based according to the following structure: <br> 1.- <b>Thesis</b> <br> 2.- <b>Confirmation</b> <br> 3.- <b>Antithesis</b> <br> 4.- <b>Supporting idea</b> <br> 5.- <b>Conclusion</b> <br><br> There are, however, a number of other structures that can be used to develop an argumentative text (Maccoun, 1983): <br> - <b>Zig zag pattern</b> <br> - <b>One-sided argument</b> <br> - <b>Eclectic approach</b>"},
            { text: "5.2. Stylistics in argumentative texts", info: "The style of an argumentative text depends on its type. Subjective texts often use first-person singular, while objective texts favour first-person plural or an impersonal linguistic style. The inclusion of the sender and the receive can make arguments feel more valid by suggesting shared viewpoints. The style that is ultimately Cuerpo de Profesores Educación Secundaria. Especialidad Inglés. Tema 34. selected depends greatly on the audience. If the audience does not share the specialised knowledge of the sender, then a greater description of details must be given, especially through the use of examples. This is known as an illustrative style. On the other hand, when the audience of the sender is more specialised on the topic, a more technical style of the language can be used. Finally, a persuasive style is used when showing desire to influence the listener to accept the sender’s point of view. This style is typically used in subjective argumentative texts, where the sender will try to trigger an emotional response in the listener."},
            { text: "6. Relevance of this topic in the classroom"},
            { text: "7. Conclusion"},
            { text: "8. Bibliography"}
        ]
    },
    {
        title: "TOPIC 35: EXPLICATIVE TEXTS. STRUCTURE AND CHARACTERISTICS",
        outline: [
            { text: "1. Introduction", info: "<b>Halliday and Hasan, 1976</b><br> Text can be defined as “a stretch of language that can form the process of communication”"},
            { text: "2. Text and context", info: "In 1923, anthropologist <b>Malinowski</b> introduced the concept of context of situation, referring to extra-linguistic factors influencing a text. He observed that cultural background shapes individual psychology, challenging Jung and Freud’s theories on the collective subconscious. While translating English texts for the Trobriand Islanders of New Guinea, he found cultural differences difficulted comprehension, leading him to provide contextual instructions for clarity. <br><br> The concept of context of situation was re-elaborated by Firth, who distinguished four main elements which have to be born in mind in relation to descriptive text: <br> - <b>The participants in the situation</b> <br> - <b>The action of the participants</b> (including verbal and non-verbal actions) <br> - The relevant features that affect the act of communication, that is, <b>the surrounding objects and events</b> <br> - <b>The effects of the verbal action</b> <br><br> Hymes categorizes the speech situation in terms of components. According to him, the higher number of known elements, the better understanding of the text. Hymes’ components are: <br> - Form and content of the message (<b>setting</b>) <br> - <b>Participants</b> (intention and effect) <br> - <b>Key communication</b> <br> - <b>Medium</b> (norms of interaction) <br> - <b>Genre</b> (type of text) <br><br> A more abstract interpretation has been offered by Halliday and Hasan. They proposed three headings: <br> - <b>Field</b> <br> - <b>Mode</b> <br> - <b>Tenor</b>"},
            { text: "3. Principles of an explicative text"},
            { text: "3.1. Regulative principles", info: "- <b>The efficiency of a text</b> <br> - <b>The effectiveness of a text</b> <br> - <b>The appropriateness of a text</b>"},
            { text: "3.2. Constitutive principles", info: "- <b>Situationality</b> <br> - <b>Informativity</b> <br> - <b>Intertextuality</b> <br> - <b>Intentionality</b> <br> - <b>Acceptability</b>"},
            { text: "4. Cohesion and coherence", info: "The feature that distinguishes a text from a disconnected sequence of sentences is <b>cohesion</b>; cohesion provides a text with <b>coherence (or texture)</b> and makes it hang together as a significant unit. In this sense, <b>Hallidday and Hasan</b> believe that a set of sentences will or will not constitute a text depending on the cohesive relationships within and between sentences, which create a <b>“texture”</b>. <br><br> According to <b>Halliday and Hasan (2014)</b>, cohesion is the combination of <b>register</b>, or how we speak, and <b>various devices</b> that make a text coherent."},
            { text: "4.1. Register", info: "Register can be divided into two classes: <br> <b>- Open Register</b> <br> <b>- Closed Register</b>"},
            { text: "4.2. Cohesive devices", info: "According to Halliday and Hasan (2014), cohesion is created through five devices: <br> - <b>Reference</b>:<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Exophoric <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Endophoric: <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9632; Anaphora <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9632; Cataphora <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Reference items <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9632; Personal pronouns <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9632; Comparatives <br>- <b>Substitution</b>:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Nominal substitution <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Verbal substitution <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Clausal substitution <br>- <b>Ellipsis</b>:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Nominal ellipsis <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Verbal ellipsis <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Clausal ellipsis <br>- <b>Lexical cohesion</b>:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Reiteration <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Collocation <br>- <b>Conjunction (Connectors and linkers)</b>:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Additive connectors <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Contrastive connectors <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Cause and result connectors <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Time connectors <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Purpose connectors <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#9900; Disjunctive connectors"},
            { text: "5. Characteristics of explicative texts", info: "Explicative texts will often make use of certain grammatical items in order to ensure that the explanation is as short, and as clear as possible."},
            { text: "5.1. Grammatical items", info: "- <b>Imperative</b> <br> - <b>Passive voice</b> <br> - <b>Ordinal numbers</b>"},
            { text: "5.2. Structure of explicative texts", info: "The maxim of Grice—<b>Be True, Brief, Relevant, and Clear</b>—applies to all texts, especially explanations. If the sender doesn’t present the explanation clearly, the message loses value. The sender’s goal is to communicate, not to show how many clever terms he knows. The structure of the explanation depends on the message. An explanation about how to make a cake, for example, would have a very different structure to one about how to use a computer. <br><br> <b>Baugh and Cable</b> note that a good explanation should make use of some or all of the following structural elements: <br> - <b>Introduction</b> <br> - <b>Revision</b> <br> - <b>Visual Aids</b> (such as highlighting, underlining, italics or bold writing) <br> - <b>Conclusion</b>"},
            { text: "6. Styles of explanation"},
            { text: "6.1. Definition"},
            { text: "6.2. Analysis"},
            { text: "6.3. Cause and effect", info: "Cause is the connection between events that conforms to the following rules: <br> <b>B happens because of A</b> <br> <b>Wherever there is A there will be B</b>"},
            { text: "6.4. Comparison and contrast"},
            { text: "6.5. Illustration"},
            { text: "7. Relevance of this topic in the classroom"},
            { text: "8. Conclusion"},
            { text: "9. Bibliography"}
        ]
    },
];

